title: "cepdnaclk.github.io"
# logo: /assets/img/logo.png
description: "Department of Computer Engineering"
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal

plugins:
    - jekyll-seo-tag
